### ISSUE TITLE
[META] Better X86 CPU targeting

### ISSUE THREAD

**Issue by LebedevRI** [halide/Halide#6682]
This is mostly a meta-issue to track sub-issues.

- [ ] Add enum with the X86 cpu's that are supported by halide
   - [x] AMD CPU's added (#6655)
   - [ ] Intel CPU's are missing
- [x] Support specifying the particular CPU for which the LLVM should tune for (#6655)
- [ ] Support auto-detecting the current host CPU
   - [X] Base framework and proof-of-concept support for a single CPU (#6648)
   - [x] Detection for other supported AMD CPU's is missing (#6711)
   - [ ] Intel CPU's are missing
- [ ] Run-time multi-version selection support for tune CPU
   - [ ] Support encoding the tune cpu for the purposes of multi-versioning
   - [ ] Host CPU auto-detection (ideally, don't duplicate the code to do that)
   - [ ] Exact match
   - [ ] Fallback in case of no exact match (???)
- [ ] Support targeting the CPU (LLVM tune+halide features) by just the CPU name, similarly to `-march=<...>` (!!!)
- [ ] Support **_precisely_** targeting the CPU (LLVM `target-cpu` + LLVM `target-features` + halide features) by just the CPU name, exactly what `-march=<...>` does (!!!!!!)
   - [ ] Support encoding the target cpu for the purposes of multi-versioning
   - [ ] Exact match
   - [ ] Fallback in case of no exact match (???)
