### ISSUE TITLE
Serialization test suite tracking issue

### ISSUE THREAD

**Issue by TH3CHARLie** [halide/Halide#7745]
once #7594 is merged, we will work on follow-up PRs to have a test suite:

- [ ] standalone AOT serialization test
- [ ] standalone JIT serialization test
- [ ] standalone serialization test (API usage)
- [ ] fuzzing serialization
